GENB/CAR/urls.py

import django
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import set_language
from CAR import views



app_name='car'

urlpatterns = [
    path('car/<slug:car_slug>/', views.car_s, name='car'),
]




    

GENB/GENB/urls.py
from argparse import Namespace
from xml.dom.minidom import Document
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include

from GENB import settings 


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('MAIN.urls', namespace='main')),
    path('catalog/', include('SPARE.urls', namespace='catalog')),
    path('car/', include('CAR.urls', namespace='car')),
    path('user/', include('USERS.urls', namespace='user')),
    path('content/', include('CONTENT.urls', namespace='content')),

]


if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),] 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GENB/SPARE/urls.py
import django
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import set_language
from SPARE import views

app_name='spare'


urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('', views.catalog, name='catalog'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('get_models/', views.get_models, name='get_models'),
    path('get_years/', views.get_years, name='get_years'),
]

GENB/SPARE/models.py
from django.db import models
from CAR.models import Car


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорію'
        verbose_name_plural = 'Категорії'

    def __str__(self) -> str:
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Підкатегорія')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL')
    category = models.ForeignKey(to=Categories, on_delete=models.SET_NULL, null=True, verbose_name='Категорія')


    class Meta:
        db_table = 'sub_category'
        verbose_name = 'Підкатегорію'
        verbose_name_plural = 'Підкатегорії'

    def __str__(self) -> str:
        return self.name


class AdditionalСategory(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL')
    sub_category = models.ForeignKey(to=SubCategory, on_delete=models.SET_NULL, null=True, verbose_name='Підкатегорія')
    

    class Meta:
        db_table = 'addit_category'
        verbose_name = 'Додаткову категорію'
        verbose_name_plural = 'Додаткові категорії'

    def __str__(self) -> str:
        return self.name



class SparePart(models.Model):

    car = models.ForeignKey('CAR.Car', on_delete=models.SET_NULL, null=True, related_name='cars', verbose_name='Автомобіль')
    oem_code = models.CharField(max_length=50, verbose_name='Оригінальний номер запчастини')
    name = models.CharField(max_length=150, verbose_name='Назва запчастини')
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, verbose_name='Категорія')
    sub_category = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True, verbose_name='Підкатегорія')
    additional_category = models.ForeignKey(AdditionalСategory, on_delete=models.SET_NULL, null=True, verbose_name='Дод.категорія')
    warehouse = models.CharField(
        max_length=100,
        choices=[
            ('swarehouse_korea', 'Склад Корея'),
            ('swarehouse_wag', 'Склад Wag'),
            ('swarehouse_return', 'Повернення'),
             ('swarehouse_reserv', 'В резерві'),
            ],
        verbose_name='Склад')
    cell = models.PositiveIntegerField(null=True, verbose_name='Ячейка')
    
    condition = models.CharField(
        max_length=50,
        choices=[
            ('new', 'Нова'),
            ('living', 'Вживана')
        ],
        default='living',
        verbose_name='Стан'
    )
    additional_condition = models.CharField(
        max_length=50,
        choices=[
            ('good','Хороший' ),
            ('satisfactory', 'Задовільний'),
            ('defective', 'З дефектом'),
            ('repaired', 'Зі слідами ремонту'),
        ], 
        blank=True,
        null=True,
        verbose_name='Додаткова умова'
    )

    
    availability = models.CharField(
        max_length=50,
        choices=[
            ('in_stock', 'В наявності'),
            ('shipped', 'Відправлено'),
            ('returned', 'Повернення'),
            ('defective', 'Брак'),
            ('written_off', 'Списано'),
        ],
        default='in_stock',
        verbose_name='Статус'
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    sku = models.CharField(max_length=50, unique=True, verbose_name='Артикул', blank=True)
    #photo = models.ImageField(upload_to='spare_parts', blank=True, null=True, verbose_name='Фото')


    class Meta:
        db_table = 'spare_part'
        verbose_name = 'Запчастина'
        verbose_name_plural = 'Запчастини'


    def __str__(self) -> str:
        if self.additional_condition:
            return f'{self.name} | Стан - {self.get_condition_display()} ({self.get_additional_condition_display()}) | Статус - {self.get_availability_display()}'
        return f'{self.name} | Стан - {self.get_condition_display()} | Статус - {self.get_availability_display()}'
    

    def save(self, *args, **kwargs):
        if not self.sku and self.car:  # Автоматичне формування артикула, якщо його немає
            vin_last_digits = self.car.vin_code[-4:]  # Останні 4 цифри VIN-коду
            self.sku = f"{vin_last_digits}0000"  # Попереднє значення артикула (замість id)
            super().save(*args, **kwargs)  # Зберегти об'єкт

        # Після збереження оновити SKU до значення "вин_last_digits + id"
            self.sku = f"{vin_last_digits}-{self.id}"
        super().save(*args, **kwargs)  # Повторне збереження з оновленим sku
 # Зберегти об'єкт вдруге з оновленим sku


class SparePartImage(models.Model):
    spareparts = models.ForeignKey(SparePart, on_delete=models.CASCADE, related_name='images')
    photo = models.ImageField(upload_to='spare_parts/')

    def __str__(self):
        if self.spareparts and self.spareparts.car:
            car = self.spareparts.car
            return f"Зображення для {car.brand} {car.model}"
        return "Зображення без прив'язки до автомобіля"


GENB/SPARE/views.py
from unicodedata import category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from CAR.models import Car
from SPARE.models import SparePart, Categories
from SPARE.forms_for_filters import CarPartFilterForm
from SPARE.utils import q_search


from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def catalog(request):
    # Фільтрація товарів
    form = CarPartFilterForm(request.GET)
    parts = SparePart.objects.all()
    query = request.GET.get('q', None)  # Правильне отримання значення 'q'

    if query:
    # Логіка пошуку за текстовим запитом (залежить від реалізації q_search)
        parts = parts.filter(name__icontains=query)  
    else:
    # Використання фільтрів з форми
        if form.is_valid():  
            if form.cleaned_data['brand_car']:
                parts = parts.filter(car__brand_car=form.cleaned_data['brand_car'])
            if form.cleaned_data['model_car']:
                parts = parts.filter(car__model_car=form.cleaned_data['model_car'])
            if form.cleaned_data['category']:
                parts = parts.filter(category__name=form.cleaned_data['category'])
            if form.cleaned_data['sub_category']:
                parts = parts.filter(sub_category__name=form.cleaned_data['sub_category'])
            if form.cleaned_data['car_spare']:
                parts = parts.filter(car__model_car=form.cleaned_data['car_spare'])
            if form.cleaned_data['oem_code']:
                parts = parts.filter(oem_code=form.cleaned_data['oem_code'])    

    # Пагінація для товарів
    page_number_goods = request.GET.get('goods_page', 1)
    try:
        page_number_goods = int(page_number_goods)
        if page_number_goods < 1:
            page_number_goods = 1
    except (ValueError, TypeError):
        page_number_goods = 1

    goods_paginator = Paginator(parts, 8)
    try:
        goods = goods_paginator.page(page_number_goods)
    except EmptyPage:
        goods = goods_paginator.page(goods_paginator.num_pages)

    # Пагінація для авто
    cars_list = Car.objects.all()
    page_number_cars = request.GET.get('cars_page', 1)
    try:
        page_number_cars = int(page_number_cars)
        if page_number_cars < 1:
            page_number_cars = 1
    except (ValueError, TypeError):
        page_number_cars = 1

    cars_paginator = Paginator(cars_list, 12)
    try:
        cars = cars_paginator.page(page_number_cars)
    except EmptyPage:
        cars = cars_paginator.page(cars_paginator.num_pages)

    # Отримання брендів, моделей та років
    brand_models = {}
    for car in cars_list:
        if car.brand_car not in brand_models:
            brand_models[car.brand_car] = {}
        if car.model_car not in brand_models[car.brand_car]:
            brand_models[car.brand_car][car.model_car] = []
        brand_models[car.brand_car][car.model_car].append(car.year)

    spare_parts_img = SparePart.objects.prefetch_related('images').all()

    # Формування контексту
    context = {
        'goods': goods,
        'cars': cars,
        'form': form,
        'brands': cars_list.values_list('brand_car', flat=True).distinct(),
        'parts': parts,
        'brand_models': brand_models,
        'cars_list': cars_list,
        'spare_parts_img': spare_parts_img,
    }
    return render(request, 'spare/catalog.html', context)



def get_models(request):
    brand = request.GET.get('brand_car')
    models = Car.objects.filter(brand_car=brand).values_list('model_car', flat=True).distinct()
    return JsonResponse({'models': list(models)})




def get_years(request):
    brand = request.GET.get('brand_car')
    model = request.GET.get('model_car')
    years = Car.objects.filter(brand_car=brand, model_car=model).values_list('year', flat=True).distinct()
    return JsonResponse({'years': list(years)})




def product(request, product_slug):

    product = get_object_or_404(SparePart, slug=product_slug)

    context = {
        'product': product
    }

    return render(request, 'goods/product.html', context)

GENB/SPARE/templates/spare/catalog.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load goods_tags %}

{% block title_meta %}
<title>{% trans "Розбирання авто | Авторозбiрка АвтоПМР | Автозапчастини б/у" %}</title>
<meta name="description" content={%
  trans "Підбір запчастин. Доставка автозапчастин здійснюється по всій Україні (Одеса, Київ, Харків, Львів, Дніпро, Запоріжжя, Чернігів)"
  %}>
{% endblock title_meta %}

{% block hero-section %}
<!-- hero-section -->
<section id="first-section" >
<div class="container">
  <div class="accordion" id="brandAccordion">
    {% for brand, models in brand_models.items %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingBrand{{ forloop.counter }}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseBrand{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseBrand{{ forloop.counter }}">
          {{ brand }}
        </button>
      </h2>
      <div id="collapseBrand{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="headingBrand{{ forloop.counter }}" data-bs-parent="#brandAccordion">
        <div class="accordion-body">
          <div class="accordion model" id="modelAccordion{{ forloop.counter }}">
            {% for model, years in models.items %}
            <div class="accordion-item-model">
              <h2 class="accordion-header-model" id="headingModel{{ forloop.counter }}">
                <button class="accordion-button-modal collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseModel{{ forloop.parentloop.counter }}{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseModel{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                  {{ model }}
                </button>
              </h2>
              <div id="collapseModel{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="accordion-collapse collapse accordion-year" aria-labelledby="headingModel{{ forloop.parentloop.counter }}{{ forloop.counter }}" data-bs-parent="#modelAccordion{{ forloop.parentloop.counter }}">
                <div class="accordion-body">
                  <ul>
                  {% for year in years %}
                  {% with cars|first_car_for_year:year as car %}
                  {% if car %}
                  <li>
                    <a href="{% url 'catalog:car' car.slug %}" class="car-card">{{ year }}</a>
                  </li>
                  {% endif %}
                  {% endwith %}
                  {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
    
      
      <div id="cars-catalog">
        {% for car in cars %}
          <a href="{% url 'catalog:car' car.slug %}" >        
            <div class="car-card">
              <div class="car-card-img">
              {% if car.photo %}
                <img src="{{ car.photo.url }}" alt="">
              {% else  %}
                <img src={% static "assets/img/image_not_foud.jpg.jpg" %} alt="">
              {% endif %}
              </div>
                <div class="car-details">
                    <h2>{{ car.brand_car }} {{ car.model_car }}</h2>
                    <p>Рік: {{ car.year }}</p>
                </div>
            </div>
          </a>
        {% endfor %}
        <!-- Пагінатор авто -->
        <div class="pagination">
            {% if cars.has_previous %}
                <a href="?cars_page={{ cars.previous_page_number }}">Попередня</a>
            {% endif %}
            <span>{{ cars.number }} з {{ cars.paginator.num_pages }}</span>
            {% if cars.has_next %}
                <a href="?cars_page={{ cars.next_page_number }}">Наступна</a>
            {% endif %}
        </div>
<div>
</section>





  <section class="catalog_zapchast">
    <div class="container">
      <h3>{% trans "Каталог товарів" %}</h3>


      
      <div class="first_screan_catalog">
        <div class="sidebar wow animate__animated animate__fadeInLeft">
          <h4>{% trans "Пошук запчастин" %}</h4>
          <form id="search-product" action=" {% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:catalog" %}{% endif %} " method="get">
            {% if request.GET.q %}
              <input type="hidden" name='q' value" {} ">
            {% endif %}
            {{ forms.as_p }}
            <label for="brand_car"></label>
            {{form.brand_car}}

            {{ forms.as_p }}
            <label for="model_car"></label>
            {{form.model_car}}

            <label for="category"></label>
            {{form.category}}

            <label for="sub_category"></label>
            {{form.sub_category}}

            <label for="car_spare"></label>
            {{form.car_spare}}

            <label for="oem_code"></label>
            {{form.oem_code}}

            <button id="search-sidebar-catalog" type="submit">{% trans " Пошук" %}</button>
          </form>
        </div>


      <div class="product-list">
        {% for product in goods %}
        <div class="product-card">
        <div class="product-stan">  </div>
          {% if product.photo %}
            <img src="{{ product.photo.url }}" alt="{{ product.sku }}">
          {% else  %}
              <img src={% static "assets/img/image_not_foud.jpg.jpg" %} alt="">
          {% endif %}
          <h3>{% trans "Артикул:" %} {{ product.sku }}</h3>
          <h3>{{ product.name }}</h3>
          <p>{% trans "Ціна:" %} {{ product.price }}</p>
          <div class="btn-cart">
            <button class="add-to-cart" data-id="{{ product.id }}" data-price="{{ product.price }}" data-name="{{ product.sku }}"  data-photo="{% if product.photo %}{{ product.photo.url }}{% else %}#{% endif %}">
              {% trans "Додати до кошика" %}
            </button>
          </div>
          <div class="product_btn">
            <a href="{% url 'catalog:product' product.slug %}">{% trans "Детальніше" %}</a>
          </div>
        </div>
        {% endfor %}
      </div>

    <!-- Пагінатор товарів -->
    <div class="pagination">
      {% if goods.has_previous %}
          <a href="?goods_page={{ goods.previous_page_number }}"><</a>
      {% endif %}
      <span>{{ goods.number }} з {{ goods.paginator.num_pages }}</span>
      {% if goods.has_next %}
          <a href="?goods_page={{ goods.next_page_number }}">></a>
      {% endif %}
  </div>
</div>
    </div>
  </section>
</section>
    
    {% comment %} </div>
    <button class="load-more">{% trans "Завантажити більше" %}</button>
  </div> {% endcomment %}
  
</section>


<section class="catalog_mark_avto">
  <div class="hero-screan">
    <div class="container">
      <h2 class="wow animate__animated wow animate__animated animate__backInUp">{% trans "Каталог запчастин" %}</h2>
      <div class="catalog">
        <ul class="catalog-list wow animate__animated animate__backInUp">
          <li><a href="#"><img src="{% static 'assets/img/acura.svg' %}" alt="acura"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/audi.svg' %}" alt="audi"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/bmw.svg' %}" alt="bmw"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/crysler.svg' %}" alt="crysler"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/dodge.svg' %}" alt="dodge"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/honda.svg' %}" alt="honda"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/hynday.svg' %}" alt="hynday"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/infiniti.svg' %}" alt="infiniti"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/jaguar.svg' %}" alt="jaguar"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/jeep.svg' %}" alt="jeep"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/linkoln.svg' %}" alt="linkoln"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/kia.svg' %}" alt="kia"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/land_rover.svg' %}" alt="landrover"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/nissan.svg' %}" alt="nissan"></a></li>
          <li><a href="#"><img src="{% static 'assets/img/volkswagen.svg' %}" alt="volkswagen"></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- Модальное окно -->
<div class="page-overlay" style="display: none;"></div> <!-- Затемняющий фон -->
<div id="cartModal" class="modal hidden">
  <div class="modal-content">
    <h3>{% trans "Товар доданий у кошик!" %}</h3>
    <p>{% trans "Ви бажаєте продовжити покупки або оформити замовлення." %}</p>
    <div class="modal-buttons">
      <button onclick="closeCartModal()">{% trans "Продовжити покупки" %}</button>
      <button onclick="proceedToCheckout()">{% trans "Оформити замовлення" %}</button>
    </div>
  </div>
</div>
</main>
{% endblock hero-section %}


GENB/SPARE/templates/spare/product.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title_meta %}
<meta name="description" content={%
  trans "Підбір запчастин. Доставка автозапчастин здійснюється по всій Україні (Одеса, Київ, Харків, Львів, Дніпро, Запоріжжя, Чернігів)"
  %}>

<title>{% trans "Деталі продукту" %}</title>
  {% endblock title_meta %}

  {% block hero-section %}
        <section class="product-section">
          <div class="container">
            <div class="product-details">
              <div class="product-image-slider">
                <ul id="imageGallery">
                </ul>
              </div>
              <div class="product-item">
                <div class="stan"></div>
                <h1 class="product-name">{% trans  product.name %}</h1>
                <div class="product-title-item articul">{% trans "Артикул:" %} {{product.sku}}<span class="product-id"></span></div>
                <div class="product-title-item">{% trans "Марка авто:" %} {{ product.car.brand_car }}<span class="product-markaavto"></span></div>
                <div class="product-title-item">{% trans "Модель:" %} {{ product.car.model_car }}<span class="product-model"></span></div>
                <div class="product-title-item">{% trans "Рік випуску:" %} {{ product.car.year }}<span class="product-god"></span></div>
                <div class="product-title-item">{% trans "ОЕМ:" %} {{ product.oem_code }} <span class="product-originalnumber"></span></div>
                <div class="product-title-item">{% trans "Категорія:" %} {{ product.category }} <span class="product-category"></span></div>
                <div class="product-title-item">{% trans "Підкатегорія:" %} {{ product.sub_category }}<span class="product-pod_category"></span></div>
                <div class="product-title-item">{% trans "Доп.категорія:" %} {{ product.additional_category }} <span class="product-dop_category"></span></div>
                <div class="product-title-item">{% trans "Паливо:"%} {{ product.car.fueld_type }} <span class="product-toplivo"></span></div>
                <div class="product-title-item">{% trans "Тип кузова:" %} {{ product.car.body_type }} <span class="product-typ_kuzova"></span></div>
                <div class="product-title-item price"><span class="product-price"></span>{{ product.price }}<span class="product-price-uah"></span></div>
                <button class="add-to-cart" data-id="${product.ID_EXT}" data-price="${product.zena}" data-tipe="${product.zapchast}">{% trans "Додати до кошика" %}</button>
                <button class="buy-now" data-id="${product.ID_EXT}" data-price="${product.zena}" data-tipe="${product.zapchast}">{% trans "Купити в 1 клік" %}</button>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="info-block">
              <div class="info-header">
                <div id="deteils" class="info-tab">{% trans "Подробиці" %}</div>
                <div id="analog" class="info-tab">{% trans "Підходить" %}</div>
                <div id="delivery" class="info-tab">{% trans "Доставка і оплата" %}</div>
                <div id="guarantees" class="info-tab">{% trans "Гарантії" %}</div>
              </div>
              <div class="deteils-info info-content">
                <div class="opysanye"></div>
              </div>
              <div class="analog-info info-content">
                <span> {% trans "авто котрим підходить ця позиція" %}</span>
              </div>
              <div class="delivery-info info-content">
                <div class="container">
                  <h1 class=" wow animate__animated animate__flipOutY">{% trans "Доставка і оплата" %}</h1>
                  <div class="delivery wow animate__animated animate__zoomIn">
                    <h2>{% trans "Доставка товару :" %}</h2>
                    <ul>
                      <li>{% trans "Самовивіз;" %}</li>
                      <li>{% trans "Кур'єрські служби Нова Пошта, Делівері;" %}</li>
                      <li>{% trans "Відправка на таксі (за рахунок покупця) по м. Київ після повної оплати;" %}</li>
                      <li>{% trans "Bеликогабаритні товари - мікроавтобусом компанії за попереднім поgodженням ціни." %}
                      </li>
                    </ul>
                  </div>
                  <div class="payment wow animate__animated animate__rollIn">
                    <h2>{% trans "Оплата:" %}</h2>
                    <ul>
                      <li>{% trans "Готівковий/безготівковий розрахунок (на рахунок ФОП без ПДВ)." %}</li>
                      <li>{% trans "При відправках кур'єрськими службами - за передоплатою на послуги перевізника в
                        обидві сторони або
                        повна оплата (за бажанням)" %}</li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="guarantees-info info-content">
                <div class="container">
                  <div class="guarantees  wow animate__animated animate__rubberBand">{% trans "Компанія GenBrothers
                    надає можливість
                    перевірки якість запчастин. " %}</div>
                  <p class="guarantees-item  wow animate__animated animate__lightSpeedInRight">{% trans "Повернути, або
                    обміняти
                    товар, можна протягом" %} <span class="guarantees-weight">{% trans "7 календарних дні в" %}</span>
                    {% trans "з моменту отримання замовлення. Термін перевірки двигунів і КПП - 7 календарних днів. " %}
                  </p>
                  <div class="guarantees-item  wow animate__animated animate__lightSpeedInLeft">{% trans "Звертаємо Вашу
                    увагу, що
                    згідно ЗУ» Про захист прав споживачів', повернення або обмін вживаного товару можливий тільки за
                    згодою
                    продавця." %}
                  </div>
                  <p class="guarantees-item  wow animate__animated animate__lightSpeedInRight">{% trans "Компанія Gen
                    Brothers бере на
                    себе, на добровільній основі ці зобов’язання згідно " %}<span class="guarantees-weight">{% trans "ЗУ
                      «Про захист прав
                      споживачів» Ч.2 статті 8. " %}</span>
                    {% trans "Умови для товарів, котрі реалізуються вже вживаними — «щодо непродовольчих товарів, які
                    перебували у
                    використанні та були реалізовані через роздрібні комісійні торговельні підприємства, вимоги
                    споживача,
                    зазначені в частині першій статті 8, задовольняються за згодою продавця. Відповідно до цієї частини
                    задовольняються вимоги споживача щодо товарів, гарантійний термін на які не закінчився»." %}
                  </p>
                  <span class="guarantees-weight  wow animate__animated animate__lightSpeedInLeft">{% trans "Не
                    підлягають поверненню
                    автозапчастини, якщо:" %}</span>
                  <ul class="guarantees-list  wow animate__animated animate__lightSpeedInRight">
                    <li>{% trans "автозапчастина була встановлена (експлуатувалася);" %}</li>
                    <li>{% trans "пошкоджена покупцем;" %}</li>
                    <li>{% trans "пломби та мітки були порушені." %}</li>
                  </ul>
                  <span class="guarantees-weight  wow animate__animated animate__lightSpeedInLeft">{% trans "Підлягають
                    поверненню
                    автозапчастини, якщо:" %}</span>
                  <ul class="guarantees-list wow animate__animated animate__lightSpeedInRight">
                    <li>{% trans "запчастина не підходить до Вашого автомобіля (за умови, що ви дали повну та правильну
                      інформацію);" %}
                    </li>
                    <li>{% trans "запчастина має приховані дефекти, що не були виявлені при покупці (необхідно надати
                      фото або відео
                      підтвердження);" %} </li>
                    <li>{% trans "пломби та мітки не порушені." %}</li>
                  </ul>
                  <span class="guarantees-importantly  wow animate__animated animate__heartBeat">{% trans "ВАЖЛИВО!!!"
                    %} </span>
                  <div id="returns">
                    <ul>
                      <li> {% trans "Протягом гарантійного терміну, забороняється проводити ремонт чи розбирання
                        запчастин;" %}
                      </li>
                      <li>{% trans "Поверненню не підлягає електрика, електроніка, мікросхеми, блоки та інші види
                        електротехнічних
                        пристроїв. У виняткових випадках повернення можливе з утриманням комісії на розсуд продавця від
                        10%
                        (але не менше 200 грн);" %}
                      </li>
                      <li>{% trans "Оренда запчастин для діагностики автомобіля складає 25% вартості запчастини, але не
                        менше 1000
                        грн. Доставку у разі оплачує покупець в обидві сторони, але для оренди не надаються:
                        електротехнічні
                        пристрої." %}
                      </li>
                      <li>{% trans "Якщо запчастина не знадобилася, при цьому немає провини компанії (напр. помилка
                        підбору клієнтом,
                        відмова кінцевого клієнта, затримка доставки з вини перевізника) стягується 10% але від вартості
                        запчастини або прийом запчастини на реалізацію та після її продажу виплата повної суми." %}
                      </li>
                    </ul>
                  </div>
                  <span class="guarantees-weight  wow animate__animated animate__heartBeat">{% trans "Повернення
                    грошових коштів
                    відбувається тільки після отримання та перевірки запчастини (до 14 днів)." %}</span>
                </div>
              </div>
            </div>
          </div>
          <div class="btn-to-catalog">
            <a href="{% url "goods:catalog" %}">{% trans "Назад до каталогу" %}</a>
          </div>

        </section>
      </main>
      {% endblock hero-section %}

   